# -*- coding: utf-8 -*-
"""TM_AI_Research_Project_Newest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gM-p9ab0EWgvVlG9c7QeCJO9xtDEkNF
"""

pip install pycaret

# ==============================
# 1. Imports
# ==============================
import pandas as pd
from pycaret.classification import *

# ==============================
# 2. Load Data
# ==============================
!wget -q https://archive.ics.uci.edu/static/public/186/wine+quality.zip
!unzip -oq wine+quality.zip
df_wine = pd.read_csv("winequality-red.csv", sep=';')

print("Original dataset shape:", df_wine.shape)
print(df_wine['quality'].value_counts().sort_index())

# ==============================
# 3. Feature Engineering
# ==============================
df_wine['total_acidity'] = df_wine['fixed acidity'] + df_wine['volatile acidity']
df_wine['alcohol_to_density'] = df_wine['alcohol'] / df_wine['density']
df_wine['sulphate_to_chloride'] = df_wine['sulphates'] / (df_wine['chlorides'] + 1e-5)

print("After feature engineering:", df_wine.shape)

# ==============================
# 4. Setup PyCaret
# ==============================
clf_setup = setup(
    data=df_wine,
    target='quality',
    session_id=42,
    normalize=True,
    normalize_method='zscore',
    fix_imbalance=False,
    remove_multicollinearity=True,
    multicollinearity_threshold=0.95,
    fold=10,
    fold_shuffle=True,
    use_gpu=False,
    verbose=True
)

# ==============================
# 5. Compare Models
# ==============================
best_model = compare_models(sort='F1')
print("Best model selected:", best_model)

# ==============================
# 6. Tune the Best Model
# ==============================
tuned_model = tune_model(best_model, optimize='F1', n_iter=50)
print("Tuned model:", tuned_model)


# ==============================
# 7. Blend Top Models
# ==============================
top3_models = compare_models(n_select=3, sort='F1')
blended_model = blend_models(top3_models, optimize='F1')
print("Blended model created.")

# ==============================
# 8. Finalize Model
# ==============================
final_model = finalize_model(blended_model)
print("Final model ready for deployment.")

# ==============================
# 9. Predictions
# ==============================
preds = predict_model(final_model)
print(preds.head())

predictions = predict_model(blended_model, data=df_wine)